// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7SGpHH0nGl9yokmDlKxJFGCqz8wYfPik',
    appId: '1:83080451541:web:a90301f200e2334468995c',
    messagingSenderId: '83080451541',
    projectId: 'indalo-padel',
    authDomain: 'indalo-padel.firebaseapp.com',
    storageBucket: 'indalo-padel.firebasestorage.app',
    measurementId: 'G-529WYTGN2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpk7X9OUOSUbfTUiZ99vKHWDxToIFnybs',
    appId: '1:83080451541:android:d599901d1ec2935768995c',
    messagingSenderId: '83080451541',
    projectId: 'indalo-padel',
    storageBucket: 'indalo-padel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdqjOnVT6pzk0H95QPee6OcniYkrN43OY',
    appId: '1:83080451541:ios:dced77e10c70462768995c',
    messagingSenderId: '83080451541',
    projectId: 'indalo-padel',
    storageBucket: 'indalo-padel.firebasestorage.app',
    iosBundleId: 'com.example.indaloPadel',
  );
}
